"""Add capacities table

Revision ID: 74e5e432f0a3
Revises: 6d8254780eaf
Create Date: 2025-12-30 12:39:09.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e5e432f0a3'
down_revision = '6d8254780eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workshop', sa.String(length=255), nullable=False),
        sa.Column('operation_id', sa.Integer(), nullable=True),
        sa.Column('machine_name', sa.String(length=255), nullable=False),
        sa.Column('machine_count', sa.Integer(), nullable=False),
        sa.Column('cycle_time', sa.Float(), nullable=False),
        sa.Column('capacity_per_hour', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capacities')
    # ### end Alembic commands ###